; Script generated by Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "SIDADU System"
#define MyAppVersion "1.0.0"
#define MyAppPublisher "Fanzhy"
#define MyAppURL "http://www.example.com/"
#define MyAppExeName "install.bat"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside Inno Setup)
AppId={{12345678-1234-1234-1234-1234567890AB}}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName=C:\xampp\htdocs\sidaduz
DisableDirPage=no
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning that {app} is the 64-bit Program Files directory and the
; 64-bit view of the registry is used.
ArchitecturesInstallIn64BitMode=x64compatible
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
OutputDir=installer_output
OutputBaseFilename=SiskoApp_Setup
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Files]
; IMPORTANT: We verify that we are packaging the 'current' directory content
Source: "*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; Exclude git, node_modules (optional, but keep for npm build if needed, though usually built assets are enough), and temp files
; For production, usually we EXCLUDE node_modules and just keep 'public/build' and 'vendor'
; But to match the previous logic of "easy install", we might include them or run install.bat to fetch them.
; Let's assume we package EVERYTHING except heavy dev folders to keep size down, but relying on install.bat to fetching dependencies is cleaner for Updates.
; However, for an "Offline Installer", we should include 'vendor' and 'node_modules'.
; For this template, I will simply include everything but exclude .git.

[Dirs]
Name: "{app}"; Permissions: users-full

[Run]
; Run the install.bat after extraction to set up env, migrations, etc.
Filename: "{app}\{#MyAppExeName}"; Description: "Run Setup Script (Database & Env)"; Flags: shellexec waituntilterminated postinstall

[UninstallDelete]
Type: filesandordirs; Name: "{app}"
